# Generated by Django 5.2.14 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="overall_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated total percentage (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
