# Generated by Django 5.2.14 on 2026-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_courseenrollment_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
    ]
