# Generated by Django 5.2.14 on 2026-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_courseenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_flagged_weak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='weak_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
