# Generated by Codex on 2026-05-20

from django.db import migrations


def normalize_legacy_statuses(apps, schema_editor):
    CourseEnrollment = apps.get_model('enrollments', 'CourseEnrollment')
    CourseEnrollment.objects.filter(status__in=['PENDING', 'REJECTED']).update(status='ENROLLED')


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_courseenrollment_is_flagged_weak_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_statuses, migrations.RunPython.noop),
    ]
