# Generated by Django 5.2.14 on 2026-05-19 21:50

import apps.academics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_coursematerial"),
        ("students", "0004_alter_student_academic_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file_attachment",
                    models.FileField(
                        help_text="Upload PDF or DOC files. Max size should be enforced in forms.",
                        upload_to=apps.academics.models.subject_book_upload_path,
                        validators=[apps.academics.models.validate_pdf_extension],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("student", "subject")},
            },
        ),
    ]
