# Generated by Django 6.0.4 on 2026-05-19 15:32

import apps.students.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        help_text="Unique admission number (e.g., STU001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Format: YYYY-MM-DD", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1"),
                            ("2", "Grade 2"),
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                            ("11", "Grade 11"),
                            ("12", "Grade 12"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a student photo (optional)",
                        null=True,
                        upload_to=apps.students.models.student_image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["-created_at"],
            },
        ),
    ]
