# Generated by Django 5.2.14 on 2026-05-19 21:26

from django.db import migrations, models

def map_academic_levels(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        old_val = student.academic_level # Field has been renamed by the previous operation
        if old_val == '1':
            student.academic_level = 'L1'
        elif old_val == '2':
            student.academic_level = 'L2'
        elif old_val == '3':
            student.academic_level = 'L3'
        else:
            student.academic_level = 'L4'
        student.save(update_fields=['academic_level'])


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="grade",
            new_name="academic_level",
        ),
        migrations.RunPython(map_academic_levels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="student",
            name="academic_level",
            field=models.CharField(
                choices=[
                    ("L1", "Level 1"),
                    ("L2", "Level 2"),
                    ("L3", "Level 3"),
                    ("L4", "Level 4"),
                ],
                default="L1",
                max_length=2,
            ),
        ),
    ]
