# Generated by Django 5.2.14 on 2026-05-19 21:30

from django.db import migrations, models

def update_level_format(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        if student.academic_level == 'L1':
            student.academic_level = 'Level 1'
        elif student.academic_level == 'L2':
            student.academic_level = 'Level 2'
        elif student.academic_level == 'L3':
            student.academic_level = 'Level 3'
        elif student.academic_level == 'L4':
            student.academic_level = 'Level 4'
        student.save(update_fields=['academic_level'])

class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_grade_student_academic_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="academic_level",
            field=models.CharField(
                choices=[
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                    ("Level 3", "Level 3"),
                    ("Level 4", "Level 4"),
                ],
                default="Level 1",
                max_length=20,
            ),
        ),
        migrations.RunPython(update_level_format, migrations.RunPython.noop),
    ]
