# Generated by Django 5.2.14 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="passing_score",
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="quiz",
            name="total_marks",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
