# Generated by Django 5.2.14 on 2026-05-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_subjectbook_studentcurriculum"),
        ("assessments", "0002_quiz_passing_score_quiz_total_marks"),
        ("students", "0004_alter_student_academic_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "Multiple Choice"), ("TF", "True/False")],
                        default="MCQ",
                        max_length=3,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="assessments.subjectquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("time_limit_minutes", models.PositiveIntegerField(default=60)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "passing_score",
                    models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_quizzes",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subjectquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.subjectquiz",
            ),
        ),
        migrations.CreateModel(
            name="SubjectQuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.subjectquiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_quiz_attempts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz", "student")},
            },
        ),
    ]
