# Generated by Django 5.2.14 on 2026-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_subjectquestion_subjectchoice_subjectquiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectquiz",
            name="num_questions",
            field=models.PositiveIntegerField(
                default=5, help_text="Number of questions required for this quiz"
            ),
        ),
    ]
